package se.rhel.event;

/**
 * Group: Logic
 * Created by Emil on 2014-03-28.
 */
public enum EventType {
    SHOOT, JUMP, GRENADE, BULLET_HOLE, EXPLOSION, DAMAGE, GRENADE_CREATED, PLAYER_JOIN, PLAYER_MOVE, SERVER_WORLD_COLLISION, SERVER_DEAD_ENTITY, CONNECTED;
}
