package se.rhel.event;

/**
 * Group: Logic
 * Created by Emil on 2014-03-28.
 */
public enum EventType {
    SHOOT, JUMP, GRENADE, BULLET_HOLE, EXPLOSION, DAMAGE, GRENADE_CREATED, PLAYERJOIN, SERVER_DEAD_ENTITY, SERVER_DAMAGED_ENTITY, SERVER_WORLD_COLLISION;
}
